-   id: ansible-check-encrypted-secrets
    name: Check Secrets Encrypted
    description: This hook checks Ansible Vault secrets are encrypted
    entry: bin/ansible-check-encrypted-secrets.sh
    language: script
    files: secrets.yml
    types: [text]

-   id: terraform-fmt
    name: Check Terraform Format
    description: This hook checks Terraform is formatteed correctly
    entry: bin/terraform-fmt.sh
    language: script
    files: \.(tf)$
    types: [terraform]

-   id: terraform-lint
    name: Check Terraform Lint
    description: This hook checks Terraform lint
    entry: bin/terraform-lint.sh
    language: script
    files: \.(tf)$
    types: [terraform]

-   id: shellcheck
    name: Test bash scripts with shellcheck
    language: script
    entry: bin/shellcheck.sh
    types: [shell]

-   id: chart-testing
    name: Test charts with helm/chart-testing
    language: system
    entry: ct lint
    files: ^charts/
    pass_filenames: false

-   id: chart-testing-docker
    name: Test charts with helm/chart-testing
    language: docker_image
    entry: quay.io/helmpack/chart-testing:v3.8.0 sh -c 'export HOME=/tmp; git config --global --add safe.directory /src; ct lint'
    files: ^charts/
    pass_filenames: false
