-   id: ansible-check-encrypted-secrets
    name: Check Secrets Encrypted
    description: This hook checks Ansible Vault secrets are encrypted
    entry: bin/ansible-check-encrypted-secrets.sh
    language: script
    files: secrets.yml
    types: [text]

-   id: terraform-fmt
    name: Check Terraform Format
    description: This hook checks Terraform is formatteed correctly
    entry: bin/terraform-fmt.sh
    language: script
    files: \.(tf)$
    types: [terraform]

-   id: terraform-lint
    name: Check Terraform Lint
    description: This hook checks Terraform lint
    entry: bin/terraform-lint.sh
    language: script
    files: \.(tf)$
    types: [terraform]
